apiVersion: v2
name: myapp
description: A Helm chart for helm-gitops-demo application

type: application

version: 1.0.0

appVersion: "1.0.0"

keywords:
  - helm
  - kubernetes
  - docker
  - gitops

home: https://github.com/Kalyani-Bambal/helm-gitops-demo

sources:
  - https://github.com/Kalyani-Bambal/helm-gitops-demo

maintainers:
  - name: Kalyani Bambal
    email: kalyani.bambal@example.com

